# .streamlit/secrets.toml
[passwords]
admin = "admin123"
sadmin = "sadmin123"
[evaluators]
"martin.zhang@ottoint.com" = "Martin Zhang"
"louis.yang@ottoint.com" = "Louis Yang"
"andy.ma@ottoint.com" = "Andy Ma"
"alan.s.huang@ottoint.com" = "Alan Huang"
"bill.cheung@ottoint.com" = "Bill Cheung"
"george.lz.zhang@ottoint.com" = "George Zhang"
"jimmy.xu@ottoint.com" = "Jimmy Xu"
"park.peng@ottoint.com" = "Park Peng"
"daly.zhou@ottoint.com" = "Daly Zhou"
"Jason Wang@ottoint.com" = "Jason Wang"
"john.shi@ottoint.com" = "John Shi"
"nick.huang@ottoint.com" = "Nick Huang"
"jim.he@ottoint.com" = "Jim He"
"julia.yu@ottoint.com" = "Julia Yu"
"jeff.li@ottoint.com" = "Jeff Li"
"betty.zhao@ottoint.com" = "Betty Zhao"
"mike.gu@ottoint.com" = "Mike Gu"
"logan.bai@ottoint.com" = "Logan Bai"
"rain.li@ottoint.com" = "Rain Li"
"tony.zhu@ottoint.com" = "Tony Zhu"
"fangfang.lv@ottoint.com" = "Fangfang Lv"
"howard.wu@ottoint.com" = "Howard Wu"
"jerry.qu@ottoint.com" = "Jerry Qu"
"alice.zhu@ottoint.com" = "Alice Zhu"
"lin.feng@ottoint.com" = "Lin Feng"
[auth_config]
cookie_key = "some_secret_string" # 随便写一串字符，用于加密
